inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'let']

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/HashSyntax:
  EnforcedShorthandSyntax: never